support v2 ip spec
apache/dubbo-spi-extensions pull request #179
Opened 2022-11-28 08:39 UTC by wxbty

## What is the purpose of the change

Support dynamic ip access for non-local clusters.

## Brief changelog

Similar to v3, build invoker for non-local cluster ip.

Currently pr only provides functions, and some codes may be shared with V3. In addition, a problem was found during the test. If the remote service times out, according to the default failover strategy, an invoker in the local cluster will be selected for execution, and an incorrect result will be obtained. This should also exist in V3 and needs to be resolved.
Issue Number: close #178 

## Verifying this change

Successful local test

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before
  you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address
  just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit
  in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency
  exist. If the new feature or significant change is committed, please remember to add sample
  in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure
  unit-test and integration-test pass.
- [ ] If this contribution is large, please follow
  the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

2022-11-28 09:23 UTC, AlbumenJ requested changes
![image](https://user-images.githubusercontent.com/9292748/204240921-36e10091-6556-4f87-9863-67b777a0a1e5.png)
Please fix check style

2022-11-29 12:28 UTC, AlbumenJ approved these changes

2022-11-29 12:28 UTC, AlbumenJ commented
![image](https://user-images.githubusercontent.com/9292748/204529254-70df9d82-c001-49eb-b097-f777271a6a5e.png)

2022-11-30 06:24 UTC, wxbty commented
> ![image](https://user-images.githubusercontent.com/9292748/204529254-70df9d82-c001-49eb-b097-f777271a6a5e.png)

Refer to the test cases of V3, because they are almost the same.

2022-12-05 03:16 UTC, merged